[project]
name = "test-grpc"
version = "0.1.0"
description = "A test project using gRPC"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.62.0",
    "grpcio-tools>=1.62.0",
    "opentelemetry-instrumentation-grpc==0.53b0",
    "protobuf>=4.25.3",
    "sentry-sdk[grpcio]==2.27.0",
]
